spring.application.name=hotel-room-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_room_management_db
spring.datasource.username=root
spring.datasource.password= GOPALTIROLE@111
spring.jpa.hibernate.ddl-auto=update
spring.main.banner-mode=off

spring.security.user.name = gopu
spring.security.user.password= Gopal@123 
spring.security.user.roles=User
